### ISSUE TITLE
cache and log volumes missing in sample docker-compose.yml and readme

### ISSUE THREAD

**Issue by hw-dwalter** [shopware/docker#103]
IMHO this leads to crazy unexpected behaviour:
```YML
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
```

also this part in readme https://github.com/shopware/docker?tab=readme-ov-file#volumes

because every worker can get different values from cache then other worker or storefront/admin. for example if you change plugin configuration value in admin your worker will never get this updated values.

i learned this lesson the hard way..

**Comment by shyim** [comment]
Hey,

It's expected that you use Redis for the data cache and logs are forwarded to the container logs (https://github.com/shopware/recipes/blob/main/shopware/docker/0.1/config/packages/docker.yaml#L26)

**Comment by shyim** [comment]
i updated the readme
