### ISSUE TITLE
Redis extension not downgradable

### ISSUE THREAD

**Issue by JoshuaBehrens** [shopware/docker#113]
In Symfony 7.1 the cache component is not compatible with ext-redis ^6.1 . So we would have to do a Symfony update 7.2. That is technically okay but randomly a reproducable hosting would not have changed the ext-redis version. I tried to pin the version in apk but the wolfi repo does not seem to make php-8.3-redis-6.0.2 available. Just 6.1.0. How would one solve this without an unexpected Symfony update?

**Comment by shyim** [comment]
This Repo has nothing together with Wolfi :)


Latest patch version of the maintained Symfony packages should solve it too. 7.1 is still maintained. 🤔 

```
apk add --no-cache php-8.3-redis=6.0.2-r2
```
works for me

**Comment by JoshuaBehrens** [comment]
AFAIK It has something to do with wolfi because the package registry is a different one and does find this package on https://pkgs.alpinelinux.org/packages . Ok, I only saw the related commit being in on 7.2 on this commit https://github.com/symfony/symfony/commit/bc22326c67fd767ba817dc33dbf142ca2f96c038 weirdly it is also on 7.1.0 which it is apparently not in our project because we require 7.1.3 of symfony/cache. I will give it a try to upgrade to 7.1.8

**Comment by shyim** [comment]
I am going to close this because it has nothing todo with Wolfi
