### ISSUE TITLE
HTTPS behind a Kubernetes Ingress with ssl termination on the AWS ELB

### ISSUE THREAD

**Issue by driv** [shopware/docker#30]
I have an nginx Ingress behind an AWS ELB. The traffic between the ingress and Shopware is http.

If I set the store address as `https://mystore.test` nginx is using http to connect to Shopware and Shopware can't find the channel: `Uncaught Exception: Unable to find a matching sales channel for the request ""http://mystore.test/"`

If I set the store address as `http://mystore.test` using http works, but if I try to use https, the browser complains about mixed content origin (It can't load any of the assets using http).

This is a very common setup and we have many other applications running this way.
Is it not possible? Can't the protocol be ignored to find the store?

**Comment by shyim** [comment]
Hey,

checkout https://symfony.com/doc/current/deployment/proxies.html, you need to set the trusted ips

**Comment by driv** [comment]
I can't find that file anywhere? Should I create it?

**Comment by shyim** [comment]
setting `TRUSTED_PROXIES` as env should be fine :D

**Comment by driv** [comment]
I've set `TRUSTED_PROXIES='REMOTE_ADDR'`

But it looks like `x-forwarded-proto` is still being ignored:

```
"headers": {
    "host": "mystore.test",
    "x-real-ip": "12.34.56.78",
    "x-forwarded-for": "12.34.56.78",
    "x-forwarded-host": "mystore.test",
    "x-forwarded-port": "80",
    "x-forwarded-proto": "https",
    "connection": "close",
    "cache-control": "max-age=0",
    "upgrade-insecure-requests": "1",
  },
  ```

**Comment by driv** [comment]
I think I've found the issue, nginx is not forwarding the proper port. `"x-forwarded-port": "80",` Omitting the port completely works, but having it set to `80` makes the request fail.

**Comment by driv** [comment]
That did not fix it.

I wanted to see what was the exact request the Nginx proxy was sending to Shopware so I added a sidecar with `socat` running in it forwarding all the traffic. That, unexpectedly, fixed the issue. Which makes me think that the problem is that Symfony is not trusting the proxy despite `TRUSTED_PROXIES='REMOTE_ADDR'` being set. 

Is there any easy way for me to debug this?

**Comment by shyim** [comment]
Hey,

We updated our Flex Recipe for Docker, so it works now by just setting TRUSTED_PROXIES env to the container with the IPs

https://github.com/shopware/recipes/commit/7379a1df96064fac0624c3c85ee29bc8207bb70b
