### ISSUE TITLE
custom plugin not showing config

### ISSUE THREAD

**Issue by DerMambo** [shopware/docker#33]
Hi :)

I have an issue adding a custom plugin. The plugin can be installed and activated, though the configuration is never showing up.

I added the plugin to a basic installation using docware and the config shows up.

Also I created a dummy plugin, basically just the default shell. Then created a new shopware prod project and created a docker image. Also for this default plugin it can be installed, activated but the config does not show.

I created a simple repo:
[https://github.com/digitale-kumpel/shopware-docker-plugin-issue](https://github.com/digitale-kumpel/shopware-docker-plugin-issue)

The plugin is in custom/plugins/DKTest

And has a config.xml

I am trying things for two days no, without any luck..... What am i missing 😭

**Comment by shyim** [comment]
Hey,

you need to require the plugin in the root composer.json, then the configuration will just work :)
