### ISSUE TITLE
Could not open input file: bin/console

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [shopware/docker#36]
i just start the example docker compose i get `Could not open input file: bin/console`

**Comment by Tjerk-Haaye-Henricus** [comment]
Does anyone care ?

**Comment by Gandalf-pro** [comment]
Doesn't work for me either.

**Comment by shyim** [comment]
What does your Dockerfile look like? The error sounds like you don't have Shopware inside the Docker container

**Comment by shyim** [comment]
Do you maybe have vendor folder in .dockerignore file?

**Comment by Tjerk-Haaye-Henricus** [comment]
Hey there,

thanks for answering :) This is how it looks like 

`
#syntax=docker/dockerfile:1.4

# pin versions
FROM ghcr.io/shopware/docker-base:8.1 as base-image
FROM ghcr.io/friendsofshopware/shopware-cli:latest-php-8.1 as shopware-cli

# build

FROM shopware-cli as build

COPY --link . /src
WORKDIR /src

COPY ./.shopware-project.yml /src/.shopware-project.yml

RUN --mount=type=secret,id=composer_auth,dst=/src/auth.json \
    --mount=type=cache,target=/root/.composer \
    --mount=type=cache,target=/root/.npm \
    /usr/local/bin/entrypoint.sh

# build final image

FROM base-image

COPY --from=build --chown=www-data /src /var/www/html
`

**Comment by shyim** [comment]
Do you have a `.dockerignore` file? 🤔

**Comment by Tjerk-Haaye-Henricus** [comment]
No i do not have one 
<img width="235" alt="image" src="https://github.com/shopware/docker/assets/44015586/e51277e2-53b6-468f-abbc-4ea6fab8e522">

**Comment by shyim** [comment]
Is it possible that you can share the complete project somewhere? :)

**Comment by Tjerk-Haaye-Henricus** [comment]
It already not working if i just use the Readme stuff. 

But here's a repo https://github.com/Tjerk-Haaye-Henricus/tmp_shopware

**Comment by shyim** [comment]
I cloned it, had to change two things in the .app.env

The database mentioned in the DATABASE_URL ended with dev_shop, but the database was not present, changed it back to just `shopware`. Also, the `APP_ENV` needs to be `prod`. Otherwise, WebProfilerBundle will be loaded and this is missing due to `composer install --no-dev`.

So my `.app.env` was looking like:

```
APP_ENV=prod
APP_SECRET=440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
INSTANCE_ID=10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
APP_URL=http://localhost
MAILER_URL=null://localhost
DATABASE_HOST=db
DATABASE_PORT=3306
DATABASE_URL=mysql://shopware:shopware@db:3306/shopware
SHOPWARE_ES_HOSTS=
SHOPWARE_ES_ENABLED=0
SHOPWARE_ES_INDEXING_ENABLED=0
SHOPWARE_ES_INDEX_PREFIX=
COMPOSER_HOME=/tmp/composer
SHOPWARE_HTTP_CACHE_ENABLED=1
SHOPWARE_HTTP_DEFAULT_TTL=7200
INSTALL_LOCALE=de-DE
```

and it was working for me.

**Comment by Tjerk-Haaye-Henricus** [comment]
Tried it but did not make any difference 
Could it be that m1 is causing the issue ?

**Comment by hasanelahi** [comment]
I'm also getting the same issue

**Comment by hasanelahi** [comment]
@shyim I create a c project with composer.json file https://github.com/shopware/production/blob/trunk/composer.json


After that i build and do docker-compose up -d container init container install plugin and all the stuff fine. While on going to web getting 500 Error. 

can you please help.
![image](https://github.com/shopware/docker/assets/98447409/f9ce93a5-fd06-4191-b8cb-81e32bba7334)
![image](https://github.com/shopware/docker/assets/98447409/98a96538-6cbf-4b42-9b19-4104ac098cef)

**Comment by shyim** [comment]
@hasanelahi does `/admin` work for you? maybe just sales channel domain config

**Comment by hasanelahi** [comment]
@shyim 
![image](https://github.com/shopware/docker/assets/98447409/bad01aa6-ef12-459d-99c0-9306a4db9e41)

**Comment by shyim** [comment]
You need to set a `JWT_PRIVATE_KEY` and `JWT_PUBLIC_KEY` environment variable.

Can be generated with `shopware-cli project generate-jwt --env` or `php bin/console system:generate-jwt-secret --use-env`

**Comment by hasanelahi** [comment]
@shyim  its work thank you very much

**Comment by xndrdev** [comment]
@Tjerk-Haaye-Henricus Works on my m3. Can you list the steps you've gone through to create your project? Maybe I can help.

**Comment by shyim** [comment]
We created an example repository with everything. https://github.com/shopwareLabs/example-docker-repository
