### ISSUE TITLE
Failed to enable Store extension

### ISSUE THREAD

**Issue by driv** [shopware/docker#40]
# Steps to reproduce

Create a new project
```
composer create-project shopware/production:6.5.0.0-dev myNewShopware
cd myNewShopware
```
Copy the Dockerfile from the README 
Copy the docker-compose.yml file from https://github.com/shopware/docker/pull/39

```
cp .env .app.env
```

Modify .app.env to have these variables:
```
DATABASE_URL=mysql://shopware:shopware@db/shopware
DATABASE_HOST=db
```
Start the containers
```
docker compose -f docker-compose.yml up -d
```

Try to activate the store through the admin console http://127.0.0.1:8000/admin#/sw/extension/store/landing-page .

# Result

```
The class "SwagExtensionStore\SwagExtensionStore" is not found. Probably an class loader error. Check your plugin composer.json
```

![Screenshot from 2023-12-15 16-12-38](https://github.com/shopware/docker/assets/2446353/017375b3-3e11-4a9b-af13-ac2509846364)

**Comment by shyim** [comment]
Hey,

we will have to disable the First Run Wizard with Docker. It's an anti-pattern to modify the docker image while running (downloading a extension)

**Comment by driv** [comment]
What would be the mechanism to install an extension? Because I was not able to install any extension.

**Comment by driv** [comment]
I'm trying to use the image to test new extensions. Is there any way to configure it to allow the installation?

**Comment by shyim** [comment]
The intended way is to require them with composer and rollout the new docker image.

**Comment by driv** [comment]
The extensions are not published yet, any way to install them in that case? Can I include them in the image?

**Comment by shyim** [comment]
You can put them normal in `custom/plugins` and run in your project `composer require <name>`. The name can you find in the `composer.json` of that project. Then it should work

**Comment by driv** [comment]
It works!

I thought it would be picked up during setup, but the composer has to already include it when building the image.

Many thanks!

**Comment by webfl0** [comment]
This issue saved me and resolved my issue, but i am wondering on a technical level how it happens that i can't activate a plugin that resides in custom/plugins using `bin/console plugin:activate`. When i start the project locally using symfony server:start this all works out and i just thought inside a docker container running php and caddy it should basically behave all the same.

Can someone explain to me the technical difference?

**Comment by shyim** [comment]
The difference is that we use always the composer plugin loader here: https://github.com/shopware/docker/blob/main/fpm/Dockerfile#L34

So the class loading is fully done by Composer and Shopware cannot add on runtime new autoloadings.

**Comment by webfl0** [comment]
> The difference is that we use always the composer plugin loader here: https://github.com/shopware/docker/blob/main/fpm/Dockerfile#L34
> 
> So the class loading is fully done by Composer and Shopware cannot add on runtime new autoloadings.

Many thanks!
