### ISSUE TITLE
Missing database tables 

### ISSUE THREAD

**Issue by enoliveira** [shopware/docker#45]
When the init container is running I'm getting this error. 

`shopware-t-init-1        | shopware-t-db-1 (172.18.0.3:3306) open
shopware-t-init-1        | Warning: Failed to load plugins. Message: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist
shopware-t-init-1        | 13:48:17 CRITICAL  [console] Error thrown while running command "system:config:get 'shopware.installed'". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:config:get 'shopware.installed'","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist"]
shopware-t-init-1        | 
shopware-t-init-1        | In ExceptionConverter.php line 49:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
shopware-t-init-1        |   or view not found: 1146 Table 'shopware.system_config' doesn't exist         
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Exception.php line 28:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
shopware-t-init-1        |   config' doesn't exist                                                        
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Connection.php line 71:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
shopware-t-init-1        |   config' doesn't exist                                                        
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | system:config:get [-s|--salesChannelId [SALESCHANNELID]] [-f|--format FORMAT] [--] <key>
shopware-t-init-1        | 
shopware-t-init-1        | Prepare installation
shopware-t-init-1        | 
shopware-t-init-1        | Created database `shopware`
shopware-t-init-1        | Imported base schema.sql
shopware-t-init-1        | 
shopware-t-init-1        | 
shopware-t-init-1        | 
shopware-t-init-1        | Get collection for identifier: "core"
shopware-t-init-1        | migrate Migrations
shopware-t-init-1        |     0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
shopware-t-init-1        | 
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Action     Number of migrations  
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Migrated   0 out of 0            
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        | 
shopware-t-init-1        | all migrations for identifier: "core" executed
shopware-t-init-1        | 
shopware-t-init-1        | Get collection for identifier: "core"
shopware-t-init-1        | migrate Migrations
shopware-t-init-1        |     0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
shopware-t-init-1        | 
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Action     Number of migrations  
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Migrated   0 out of 0            
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        | 
shopware-t-init-1        | all migrations for identifier: "core" executed
shopware-t-init-1        | 
shopware-t-init-1        | Shop configured successfully
shopware-t-init-1        | 
shopware-t-init-1        | 13:48:18 CRITICAL  [console] Error thrown while running command "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist"]
shopware-t-init-1        | 
shopware-t-init-1        | In ExceptionConverter.php line 49:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
shopware-t-init-1        |   or view not found: 1146 Table 'shopware.language' doesn't exist              
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Exception.php line 28:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
shopware-t-init-1        |   e' doesn't exist                                                             
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Statement.php line 130:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
shopware-t-init-1        |   e' doesn't exist                                                             
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | system:configure-shop [--shop-name SHOP-NAME] [--shop-email SHOP-EMAIL] [--shop-locale SHOP-LOCALE] [--shop-currency SHOP-CURRENCY] [-n|--no-interaction]
shopware-t-init-1        | 
shopware-t-init-1 exited with code 255
`

Sorry for the format. 

![image](https://github.com/shopware/docker/assets/44368472/c951acfb-1613-4fa6-8676-3b078d56e50d)

**Comment by shyim** [comment]
Is it possible for you upload the complete log?

It should go to the else block here and install https://github.com/shopware/docker/blob/main/rootfs/setup#L28-L46

**Comment by enoliveira** [comment]
@shyim Here is the complete log.

`2024-01-17 08:48:16 shopware-t-db-1 (172.18.0.3:3306) open
2024-01-17 08:48:16 Warning: Failed to load plugins. Message: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist
2024-01-17 08:48:17 13:48:17 CRITICAL  [console] Error thrown while running command "system:config:get 'shopware.installed'". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:config:get 'shopware.installed'","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist"]
2024-01-17 08:48:17 
2024-01-17 08:48:17 In ExceptionConverter.php line 49:
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
2024-01-17 08:48:17   or view not found: 1146 Table 'shopware.system_config' doesn't exist         
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17 
2024-01-17 08:48:17 In Exception.php line 28:
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
2024-01-17 08:48:17   config' doesn't exist                                                        
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17 
2024-01-17 08:48:17 In Connection.php line 71:
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
2024-01-17 08:48:17   config' doesn't exist                                                        
2024-01-17 08:48:17                                                                                
2024-01-17 08:48:17 
2024-01-17 08:48:17 system:config:get [-s|--salesChannelId [SALESCHANNELID]] [-f|--format FORMAT] [--] <key>
2024-01-17 08:48:17 
2024-01-17 08:48:18 all migrations for identifier: "core" executed
2024-01-17 08:48:18 
2024-01-17 08:48:18 Shop configured successfully
2024-01-17 08:48:18 
2024-01-17 08:48:18 13:48:18 CRITICAL  [console] Error thrown while running command "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist"]
2024-01-17 08:48:18 
2024-01-17 08:48:18 In ExceptionConverter.php line 49:
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
2024-01-17 08:48:18   or view not found: 1146 Table 'shopware.language' doesn't exist              
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18 
2024-01-17 08:48:18 In Exception.php line 28:
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
2024-01-17 08:48:18   e' doesn't exist                                                             
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18 
2024-01-17 08:48:18 In Statement.php line 130:
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
2024-01-17 08:48:18   e' doesn't exist                                                             
2024-01-17 08:48:18                                                                                
2024-01-17 08:48:18 
2024-01-17 08:48:18 system:configure-shop [--shop-name SHOP-NAME] [--shop-email SHOP-EMAIL] [--shop-locale SHOP-LOCALE] [--shop-currency SHOP-CURRENCY] [-n|--no-interaction]
2024-01-17 08:48:18 
`

**Comment by shyim** [comment]
Can you check which tables are present in the database?

**Comment by enoliveira** [comment]
They are not. How are the tables created? 

![image](https://github.com/shopware/docker/assets/44368472/dff4561b-c291-4200-9bee-0527dcfd60ba)

**Comment by shyim** [comment]
Can you delete the migration and plugin table and rerun the `init`?

**Comment by enoliveira** [comment]
I did. The same error.

![image](https://github.com/shopware/docker/assets/44368472/56eacb1f-1d49-4dc5-89a5-dab2a2cca791)


keh-JNYQY74X52:shopware-t eoliveira$ docker-compose up
[+] Running 4/0
 ⠿ Container shopware-t-opensearch-1  Running                                                                                                                                                                                                                                                                        0.0s
 ⠿ Container shopware-t-init-perm-1   Created                                                                                                                                                                                                                                                                        0.0s
 ⠿ Container shopware-t-db-1          Running                                                                                                                                                                                                                                                                        0.0s
 ⠿ Container shopware-t-init-1        Created                                                                                                                                                                                                                                                                        0.0s
Attaching to shopware-t-db-1, shopware-t-init-1, shopware-t-init-perm-1, shopware-t-opensearch-1, shopware-t-web-1
shopware-t-init-perm-1 exited with code 0
shopware-t-init-1        | shopware-t-db-1 (172.18.0.3:3306) open
shopware-t-init-1        | Warning: Failed to load plugins. Message: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.plugin' doesn't exist
shopware-t-init-1        | 14:27:40 CRITICAL  [console] Error thrown while running command "system:config:get 'shopware.installed'". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:config:get 'shopware.installed'","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_config' doesn't exist"]
shopware-t-init-1        | 
shopware-t-init-1        | In ExceptionConverter.php line 49:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
shopware-t-init-1        |   or view not found: 1146 Table 'shopware.system_config' doesn't exist         
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Exception.php line 28:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
shopware-t-init-1        |   config' doesn't exist                                                        
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Connection.php line 71:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.system_  
shopware-t-init-1        |   config' doesn't exist                                                        
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | system:config:get [-s|--salesChannelId [SALESCHANNELID]] [-f|--format FORMAT] [--] <key>
shopware-t-init-1        | 
shopware-t-init-1        | Prepare installation
shopware-t-init-1        | 
shopware-t-init-1        | Created database `shopware`
shopware-t-init-1        | Imported base schema.sql
shopware-t-init-1        | 
shopware-t-init-1        | 
shopware-t-init-1        | 
shopware-t-init-1        |  [ERROR] Cannot create private key /var/www/html/config/jwt/private.pem, it     
shopware-t-init-1        |          already exists.                                                        
shopware-t-init-1        | 
shopware-t-init-1        | 
shopware-t-init-1        | Get collection for identifier: "core"
shopware-t-init-1        | migrate Migrations
shopware-t-init-1        |     0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
shopware-t-init-1        | 
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Action     Number of migrations  
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Migrated   0 out of 0            
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        | 
shopware-t-init-1        | all migrations for identifier: "core" executed
shopware-t-init-1        | 
shopware-t-init-1        | Get collection for identifier: "core"
shopware-t-init-1        | migrate Migrations
shopware-t-init-1        |     0 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]
shopware-t-init-1        | 
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Action     Number of migrations  
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        |   Migrated   0 out of 0            
shopware-t-init-1        |  ---------- ---------------------- 
shopware-t-init-1        | 
shopware-t-init-1        | all migrations for identifier: "core" executed
shopware-t-init-1        | 
shopware-t-init-1        | Shop configured successfully
shopware-t-init-1        | 
shopware-t-init-1        | 14:27:40 CRITICAL  [console] Error thrown while running command "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException { …},"command" => "system:configure-shop --shop-locale=en-US --shop-currency=USD --no-interaction=1","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.language' doesn't exist"]
shopware-t-init-1        | 
shopware-t-init-1        | In ExceptionConverter.php line 49:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   An exception occurred while executing a query: SQLSTATE[42S02]: Base table   
shopware-t-init-1        |   or view not found: 1146 Table 'shopware.language' doesn't exist              
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Exception.php line 28:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
shopware-t-init-1        |   e' doesn't exist                                                             
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | In Statement.php line 130:
shopware-t-init-1        |                                                                                
shopware-t-init-1        |   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shopware.languag  
shopware-t-init-1        |   e' doesn't exist                                                             
shopware-t-init-1        |                                                                                
shopware-t-init-1        | 
shopware-t-init-1        | system:configure-shop [--shop-name SHOP-NAME] [--shop-email SHOP-EMAIL] [--shop-locale SHOP-LOCALE] [--shop-currency SHOP-CURRENCY] [-n|--no-interaction]
shopware-t-init-1        | 
shopware-t-init-1 exited with code 255
service "init" didn't completed successfully: exit 255
keh-JNYQY74X52:shopware-t eoliveira$

**Comment by shyim** [comment]
Is it possible that you share your docker-compose.yml?

**Comment by enoliveira** [comment]
version: "3.8"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'shopware'
            MYSQL_USER: shopware
            MYSQL_PASSWORD: shopware
            MYSQL_DATABASE: shopware
        volumes:
            - mysql-data:/var/lib/mysql

    init-perm:
        image: alpine
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        command: chown 82:82 /var/www/html/files /var/www/html/public/theme /var/www/html/public/media /var/www/html/public/thumbnail /var/www/html/public/sitemap

    init:
        image: gcr.io/it-department-150323/shopware-docker
        build:
            context: .
        env_file: .app.env
        entrypoint: /setup
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            db:
                condition: service_started
            init-perm:
                condition: service_completed_successfully
    web:
        image: gcr.io/it-department-150323/shopware-docker
        build:
            context: .
        volumes:
            - files:/var/www/html/files
            - theme:/var/www/html/public/theme
            - media:/var/www/html/public/media
            - thumbnail:/var/www/html/public/thumbnail
            - sitemap:/var/www/html/public/sitemap
        depends_on:
            init:
                condition: service_completed_successfully
        env_file: .app.env
        ports:
            - 8000:8000

#    worker:
#        image: gcr.io/it-department-150323/shopware-docker
#        restart: unless-stopped
#        build:
#            context: .
#        volumes:
#            - files:/var/www/html/files
#            - theme:/var/www/html/public/theme
#            - media:/var/www/html/public/media
#            - thumbnail:/var/www/html/public/thumbnail
#            - sitemap:/var/www/html/public/sitemap
#        depends_on:
#            init:
#                condition: service_completed_successfully
#        env_file: .app.env
#        entrypoint: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=300", "--memory-limit=512M" ]
#        deploy:
#            replicas: 1

    opensearch:
        image: opensearchproject/opensearch:2
        volumes:
            - opensearch-data:/usr/share/opensearch/data
        environment:
            discovery.type: single-node


volumes:
    mysql-data:
    files:
    theme:
    media:
    thumbnail:
    sitemap:
    opensearch-data:

**Comment by shyim** [comment]
We yesterday had the same problem. The problem was triggered as the var/cache folder was not writable. Maybe the similar problem there. Did you adjusted something in the Dockerfile?
