### ISSUE TITLE
The class "SwagExtensionStore\SwagExtensionStore" is not found. Probably an class loader error. Check your plugin composer.json

### ISSUE THREAD

**Issue by enoliveira** [shopware/docker#47]
![image](https://github.com/shopware/docker/assets/44368472/343bcea9-eb8a-4f53-8c48-4df8c5b8e2ff)

**Comment by shyim** [comment]
Hey,

This error is kinda "expected". We don't allow installing Plugins while Shopware is running. We should turn off the First Run Wizard that downloads this extension.
