### ISSUE TITLE
scheduled tasks are not running automaticly

### ISSUE THREAD

**Issue by einz-loggik** [shopware/docker#64]
Hi,

there is an issue with the scheduled tasks and production docker. If you build the container with shopware-cli and start it, the scheduled tasks are not running automaticly.

I was able to reproduce it with the example Dockerfile and docker-compose from the readme with shopware-cli 0.4.19 and shopware version 6.5.8.2.

I can manually run scheduled-task:run inside the container and the tasks get executed again so its not an immediate problem but a fix would be great.

I have no idea what caused this. I know in older versions everything worked just fine.
If i can help finding the cause let me know.

**Comment by shyim** [comment]
ahh yes the example docker-compose is missing the service for scheduled task
