### ISSUE TITLE
COMPOSER_PLUGIN_LOADER missing in ENV var list of README

### ISSUE THREAD

**Issue by dashart-ke** [shopware/docker#86]
@shyim Thank you for adding the composer notice on 23th of May.

In README.md, please extend the ENV var list by
- COMPOSER_PLUGIN_LOADER has a default value of 1
too

https://github.com/shopware/docker/blob/main/fpm/Dockerfile

That would help to understand this ENV var and provide a proper starting point for research in sw6 docs.
https://developer.shopware.com/docs/guides/hosting/installation-updates/cluster-setup.html#composer-plugin-loader

That would help to prevent bad experiences like:
https://issues.shopware.com/issues/NEXT-36879

**Comment by shyim** [comment]
fixed with https://github.com/shopware/docker/commit/c7833ef181f75f42c0700fa1ad92cad226840cf8
