### ISSUE TITLE
Wait for S3 to be ready

### ISSUE THREAD

**Issue by mitelg** [shopware/docker#88]
before the setup script is executed it waits for MySQL to be ready. The same should happen for the S3 connection, if used.

**Comment by shyim** [comment]
This makes no sense at all. This should be part of the operator. That we wait for MySQL is already a hack, and should not be extended

**Comment by mitelg** [comment]
@TrayserCassa what do you think?

**Comment by TrayserCassa** [comment]
I added this already to the operator, but if we are talking from a general perspective then it would make sense to write a command for a short check, or am I wrong?

**Comment by mitelg** [comment]
should this command then go into Shopware directly? :thinking:

**Comment by mitelg** [comment]
@shyim maybe this could be part of the new health Check in Shopware?
