### ISSUE TITLE
Introduce deployment helper

### ISSUE THREAD

**Issue by mitelg** [shopware/docker#90]
The [Shopware deployment-helper](https://github.com/shopware/deployment-helper) should be introduced to this docker image. 

This should be done before working on shopware/deployment-helper#5 

The current setup script should be deprecated. 

Check if the helper is present and then use it. If it is not yet available, use current setup script

**Comment by msestendrup** [comment]
What do you think this issue's priority should be for the Private Beta?

**Comment by shyim** [comment]
before and it's not much work 30m or so

**Comment by shyim** [comment]
fixed by https://github.com/shopware/docker/pull/98
