### ISSUE TITLE
Theme not loaded in browser

### ISSUE THREAD

**Issue by evanjamesjackson** [shopware/docker#91]
Hello - 

I have created a custom Shopware theme that I am compiling with `theme:compile`. I can see that the two expected theme folders are created under `/var/www/html/public/theme`:
![image](https://github.com/shopware/docker/assets/5866481/4311526c-2646-462f-8c51-1cc21b57b29b)

I can confirm that my Storefront sales channel is using this theme:
![image](https://github.com/shopware/docker/assets/5866481/f90f9026-5962-4b32-b6a6-56baf9864bcc)

However, when I load the site, only the `9bf1323b98bdec27166ca597bfbcdaea` folder is being loaded, and only its CSS file (no JS):
![image](https://github.com/shopware/docker/assets/5866481/0743c341-5673-4125-8ed9-83f77b463e4d)

In contrast, when running Dockware with the same theme, both folders and all associated CSS and JS are loaded (disregard different GUIDs for the theme folders as this is a different installation):
![image](https://github.com/shopware/docker/assets/5866481/d7900096-72b0-4bd6-a25d-654138b93b46)

Is there some step I'm missing in getting both themes to appear when using this Docker image?

**Comment by evanjamesjackson** [comment]
An update on this - I have discovered that removing this line https://github.com/shopware/docker/blob/c89dd1d351bf8d1c96fc98c64f12bfd3eb83495f/fpm/rootfs/usr/local/etc/php-fpm.d/docker.conf#L10 makes my theme load properly. Obviously though that breaks environment variables - is there a known way to work around this?

**Comment by shyim** [comment]
How does your compose / k8s config look like. Do you use s3 for storage or just mounts?

**Comment by JOPA159** [comment]
Hi I have the same problem as @evanjamesjackson. I am using the example compose config from the README with only volumes, not s3. Is there any solution to this problem?

**Comment by evanjamesjackson** [comment]
> How does your compose / k8s config look like. Do you use s3 for storage or just mounts?

Sorry for the delay @shyim. I'm using Docker Compose volume mounts same as @JOPA159 above.

**Comment by aritas1** [comment]
Im hitting the same problem. docker compose with local volume mounts on my end. for now there is no s3 or k8s involved.

**Comment by JOPA159** [comment]
Try installing the custom Shopware theme using composer. It solved the problem for me.

**Comment by shyim** [comment]
I would also say it's not relatable to that.

**Comment by shyim** [comment]
This is fixed by #101
